version: "3.8"

services:
  pufferpanel:
    image: pufferpanel/pufferpanel:latest
    container_name: pufferpanel
    cap_add:
      - NET_ADMIN
    network_mode: "host"
    volumes:
      - ./pufferpanel:/var/lib/pufferpanel  # Persistência de dados
    restart: unless-stopped
